[package]
name = "gt-logfile"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
gt-fmt = { path = "../gt-fmt" }
gt-geo-math = { path = "../gt-geo-math" }
gt-types = { path = "../gt-types" }
log.workspace = true
memchr.workspace = true
rayon.workspace = true
rustc-hash.workspace = true
strum.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
gt-test-utils = { path = "../gt-test-utils" }
proptest.workspace = true
rstest.workspace = true

[[bench]]
name = "parse_log"
harness = false

[lints]
workspace = true
