[package]
name = "gt-logfile"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
gt-fmt = { path = "../gt-fmt" }
gt-types = { path = "../gt-types" }
thiserror.workspace = true

[dev-dependencies]
gt-test-utils = { path = "../gt-test-utils" }
proptest.workspace = true
rstest.workspace = true

[lints]
workspace = true
