[package]
name = "gt-db"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
dirs.workspace = true
gt-types = { path = "../gt-types" }
hdf5-pure.workspace = true
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
