[package]
name = "gt-track-builder"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
geotrace-sdk-units = { path = "../../sdk/rust/geotrace-sdk-units" }
gt-analysis = { path = "../gt-analysis" }
gt-geo-math = { path = "../gt-geo-math" }
gt-types = { path = "../gt-types" }
rstar.workspace = true
rustc-hash.workspace = true
uom.workspace = true
vec1.workspace = true

[dev-dependencies]
proptest.workspace = true
rstest.workspace = true

[lints]
workspace = true
