[package]
name = "gt-instance-lock"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
fd-lock.workspace = true
gt-pending-writes = { path = "../gt-pending-writes" }
log.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
rstest.workspace = true
tempfile.workspace = true

[lints]
workspace = true
