[package]
name = "gt-history-backend-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
gt-types = { path = "../gt-types" }
hdf5 = { package = "hdf5-metno", version = "0.12.5", features = ["static", "zlib"] }
log.workspace = true
parking_lot.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true
