[package]
name = "gt-history-backend-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
gt-history-types = { path = "../gt-history-types" }
hdf5.workspace = true
log.workspace = true
parking_lot.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true
