[package]
name = "gt-plot"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
egui.workspace = true
egui-phosphor.workspace = true
egui_plot.workspace = true
geotrace-sdk-units = { path = "../../sdk/rust/geotrace-sdk-units" }
gt-analysis = { path = "../gt-analysis" }
gt-egui-mipmap = { path = "../gt-egui-mipmap" }
gt-filter = { path = "../gt-filter" }
gt-types = { path = "../gt-types" }
gt-ui-theme = { path = "../gt-ui-theme" }
gt-ui-types = { path = "../gt-ui-types" }
rayon.workspace = true
strum.workspace = true
uom.workspace = true

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
