[package]
name = "gt-fetch"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
gt-types = { path = "../gt-types" }
parking_lot.workspace = true
reqwest.workspace = true
thiserror.workspace = true

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
