// @generated by generate_bindings.rs
#ifndef GEOTRACE_CONVERSION_FACTORS_HPP
#define GEOTRACE_CONVERSION_FACTORS_HPP

namespace geotrace::detail {

/** The Rust SDK's `geotrace_sdk_units::MPS_PER_KMH`. */
inline constexpr double kMpsPerKmh = 0.2777777777777778;

/** The Rust SDK's `geotrace_sdk_units::MPS_PER_KNOT`. */
inline constexpr double kMpsPerKnot = 0.5144444444444445;

} // namespace geotrace::detail

#endif // GEOTRACE_CONVERSION_FACTORS_HPP
