// @generated by generate_bindings.rs
#ifndef GEOTRACE_UNIT_CATALOG_HPP
#define GEOTRACE_UNIT_CATALOG_HPP

#include <cstdint>

namespace geotrace {

/**
 * A unit GeoTrace recognizes, with a physical quantity and a conversion factor.
 *
 * Enumerators are named after the canonical label, with `/` written as `Per`:
 * `KmPerH` is `km/h` and `MPerS2` is `m/s2`. `G` is standard gravity, with
 * `Mg` and `Ug` its thousandth and millionth.
 */
enum class RecognizedUnit : std::uint8_t {
    Deg,
    M,
    Nm,
    Um,
    Mm,
    Cm,
    Km,
    KmPerH,
    MPerS,
    MmPerS,
    CmPerS,
    Kn,
    MPerS2,
    MmPerS2,
    CmPerS2,
    G,
    Ug,
    Mg,
    KmPerHPerS,
    Ns,
    Us,
    Ms,
    S,
    Min,
    H,
    Percent,
    PerS,
    PerMin,
    PerH,
};

/** The canonical label of @p unit, or NULL for a value outside the enum. */
inline const char *recognized_unit_label(RecognizedUnit unit) {
    switch (unit) {
    case RecognizedUnit::Deg:
        return "deg";
    case RecognizedUnit::M:
        return "m";
    case RecognizedUnit::Nm:
        return "nm";
    case RecognizedUnit::Um:
        return "um";
    case RecognizedUnit::Mm:
        return "mm";
    case RecognizedUnit::Cm:
        return "cm";
    case RecognizedUnit::Km:
        return "km";
    case RecognizedUnit::KmPerH:
        return "km/h";
    case RecognizedUnit::MPerS:
        return "m/s";
    case RecognizedUnit::MmPerS:
        return "mm/s";
    case RecognizedUnit::CmPerS:
        return "cm/s";
    case RecognizedUnit::Kn:
        return "kn";
    case RecognizedUnit::MPerS2:
        return "m/s2";
    case RecognizedUnit::MmPerS2:
        return "mm/s2";
    case RecognizedUnit::CmPerS2:
        return "cm/s2";
    case RecognizedUnit::G:
        return "g";
    case RecognizedUnit::Ug:
        return "ug";
    case RecognizedUnit::Mg:
        return "mg";
    case RecognizedUnit::KmPerHPerS:
        return "km/h/s";
    case RecognizedUnit::Ns:
        return "ns";
    case RecognizedUnit::Us:
        return "us";
    case RecognizedUnit::Ms:
        return "ms";
    case RecognizedUnit::S:
        return "s";
    case RecognizedUnit::Min:
        return "min";
    case RecognizedUnit::H:
        return "h";
    case RecognizedUnit::Percent:
        return "%";
    case RecognizedUnit::PerS:
        return "per s";
    case RecognizedUnit::PerMin:
        return "per min";
    case RecognizedUnit::PerH:
        return "per h";
    }
    return nullptr;
}

} // namespace geotrace

#endif // GEOTRACE_UNIT_CATALOG_HPP
