[package]
name = "gt-log-view"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
gt-fmt = { path = "../gt-fmt" }
gt-loaded-files = { path = "../gt-loaded-files" }
gt-logfile = { path = "../gt-logfile" }
gt-types = { path = "../gt-types" }
log.workspace = true

[dev-dependencies]
gt-test-utils = { path = "../gt-test-utils" }
rstest.workspace = true

[lints]
workspace = true
