[package]
name = "gt-log-view"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
gt-fmt = { path = "../gt-fmt" }
gt-history-types = { path = "../gt-history-types" }
gt-loaded-files = { path = "../gt-loaded-files" }
gt-logfile = { path = "../gt-logfile" }
gt-types = { path = "../gt-types" }
gt-ui-types = { path = "../gt-ui-types" }
log.workspace = true
memchr.workspace = true
parking_lot.workspace = true
rayon.workspace = true
regex.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
gt-test-utils = { path = "../gt-test-utils" }
proptest.workspace = true
rstest.workspace = true

[[bench]]
name = "filter_log"
harness = false

[lints]
workspace = true
