[package]
name = "gt-history-backend-pure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
gt-types = { path = "../gt-types" }
hdf5-pure.workspace = true
log.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
