#![expect(
    clippy::expect_used,
    reason = "formatting into an in-memory String is infallible"
)]

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use geotrace_sdk_units::Unit;

mod python_enums;

struct CppConversionFactor {
    cpp_name: &'static str,
    rust_name: &'static str,
    value: f64,
}

/// Writes `rust_name` and `value` from one identifier, so the two agree in every row.
macro_rules! cpp_conversion_factor {
    ($cpp_name:ident, $rust_name:ident) => {
        CppConversionFactor {
            cpp_name: stringify!($cpp_name),
            rust_name: stringify!($rust_name),
            value: geotrace_sdk_units::$rust_name,
        }
    };
}

const CPP_CONVERSION_FACTORS: [CppConversionFactor; 2] = [
    cpp_conversion_factor!(kMpsPerKmh, MPS_PER_KMH),
    cpp_conversion_factor!(kMpsPerKnot, MPS_PER_KNOT),
];

fn generated_files(root: &Path) -> [(PathBuf, String); 5] {
    let mut cpp = String::from(
        "// @generated by geotrace-sdk-binding-generator\n#ifndef GEOTRACE_UNIT_CATALOG_HPP\n#define GEOTRACE_UNIT_CATALOG_HPP\n\n#include <cstdint>\n\nnamespace geotrace {\n\n",
    );
    cpp.push_str(
        "/**\n * A unit GeoTrace recognizes, with a physical quantity and a conversion factor.\n *\n * Enumerators are named after the canonical label, with `/` written as `Per`:\n * `KmPerH` is `km/h` and `MPerS2` is `m/s2`. `G` is standard gravity, with\n * `Mg` and `Ug` its thousandth and millionth.\n */\n",
    );
    cpp.push_str("enum class RecognizedUnit : std::uint8_t {\n");
    for binding in Unit::BINDINGS {
        writeln!(cpp, "    {},", binding.cpp).expect("writing to a String cannot fail");
    }
    cpp.push_str("};\n\n/** The canonical label of @p unit, or NULL for a value outside the enum. */\ninline const char *recognized_unit_label(RecognizedUnit unit) {\n    switch (unit) {\n");
    for binding in Unit::BINDINGS {
        write!(
            cpp,
            "    case RecognizedUnit::{}:\n        return \"{}\";\n",
            binding.cpp,
            binding.unit.label()
        )
        .expect("writing to a String cannot fail");
    }
    cpp.push_str(
        "    }\n    return nullptr;\n}\n\n} // namespace geotrace\n\n#endif // GEOTRACE_UNIT_CATALOG_HPP\n",
    );

    let mut rust = String::from(
        "// @generated by geotrace-sdk-binding-generator\n#[pymethods]\n#[allow(non_snake_case, reason = \"Python unit constants follow the conventional uppercase spelling\")]\nimpl PyUnit {\n",
    );
    for binding in Unit::BINDINGS {
        write!(
            rust,
            "#[classattr]\nfn {}() -> Self {{ Self {{ inner: Unit::{} }} }}\n",
            binding.python, binding.rust
        )
        .expect("writing to a String cannot fail");
    }
    rust.push_str(
        "#[getter]\nfn label(&self) -> String { self.inner.to_string() }\nfn __str__(&self) -> String { self.inner.to_string() }\nfn __repr__(&self) -> String { format!(\"Unit({:?})\", self.inner.to_string()) }\nfn __hash__(&self) -> u64 { let mut hasher = DefaultHasher::new(); self.inner.hash(&mut hasher); hasher.finish() }\n}\n",
    );

    let mut pyi = String::from(
        "# @generated by geotrace-sdk-binding-generator\n\nfrom . import Unit as _Unit\n\nclass UnitCatalog:\n    \"\"\"The recognized units, inherited as class attributes of :class:`Unit`.\"\"\"\n\n",
    );
    for binding in Unit::BINDINGS {
        writeln!(pyi, "    {}: _Unit", binding.python).expect("writing to a String cannot fail");
    }

    let mut cpp_conversion_factors = String::from(
        "// @generated by geotrace-sdk-binding-generator\n#ifndef GEOTRACE_CONVERSION_FACTORS_HPP\n#define GEOTRACE_CONVERSION_FACTORS_HPP\n\nnamespace geotrace::detail {\n",
    );
    for factor in CPP_CONVERSION_FACTORS {
        // `{:?}` writes the shortest decimal that parses back to the same bits.
        write!(
            cpp_conversion_factors,
            "\n/** The Rust SDK's `geotrace_sdk_units::{}`. */\ninline constexpr double {} = {:?};\n",
            factor.rust_name, factor.cpp_name, factor.value
        )
        .expect("writing to a String cannot fail");
    }
    cpp_conversion_factors.push_str(
        "\n} // namespace geotrace::detail\n\n#endif // GEOTRACE_CONVERSION_FACTORS_HPP\n",
    );

    [
        (root.join("cpp/include/geotrace/unit_catalog.hpp"), cpp),
        (
            root.join("cpp/include/geotrace/conversion_factors.hpp"),
            cpp_conversion_factors,
        ),
        (root.join("python/geotrace-py/src/unit_catalog.rs"), rust),
        (
            root.join("python/geotrace-py/python/geotrace_sdk/_unit_catalog.pyi"),
            pyi,
        ),
        (
            root.join("python/geotrace-py/python/geotrace_sdk/enums.py"),
            python_enums::render_enums_module(),
        ),
    ]
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?).join("../..");
    let check = env::args().any(|arg| arg == "--check");
    for (path, contents) in generated_files(&root) {
        if check {
            if fs::read_to_string(&path)? != contents {
                return Err(format!("{} is stale", path.display()).into());
            }
        } else {
            fs::write(path, contents)?;
        }
    }
    Ok(())
}
