use std::fmt::{self, Debug, Display, Formatter, Write as _};

use geotrace_sdk::{Constellation, MarkerIcon, TravelMode};
use heck::ToShoutySnakeCase as _;
use strum::IntoEnumIterator as _;

pub(crate) fn render_enums_module() -> String {
    let classes = [
        PythonEnumClass {
            name: "Constellation",
            docstring: "GNSS constellation identifier.",
            members: Constellation::iter()
                .map(|constellation| {
                    PythonEnumMember::new(
                        &constellation,
                        PythonEnumValue::WireCode(constellation.wire_code()),
                    )
                })
                .collect(),
        },
        PythonEnumClass {
            name: "MarkerIcon",
            docstring: "Visual icon for a map annotation marker.",
            members: MarkerIcon::iter()
                .map(|icon| {
                    PythonEnumMember::new(&icon, PythonEnumValue::WireCode(icon.wire_code()))
                })
                .collect(),
        },
        PythonEnumClass {
            name: "TravelMode",
            docstring: "Platform a recording was made on, declared by the recorder.",
            members: TravelMode::iter()
                .filter(|mode| !matches!(mode, TravelMode::Unknown(_)))
                .map(|mode| {
                    PythonEnumMember::new(&mode, PythonEnumValue::WireName(mode.name().to_owned()))
                })
                .collect(),
        },
    ];
    let class_names = classes
        .iter()
        .map(|class| format!("\"{}\"", class.name))
        .collect::<Vec<_>>()
        .join(", ");
    let mut module = format!(
        "# @generated by geotrace-sdk-binding-generator\n\"\"\"The enumerations the SDK exchanges with the extension module.\"\"\"\n\nfrom __future__ import annotations\n\nfrom enum import Enum\n\n__all__ = [{class_names}]\n"
    );
    for class in classes {
        write!(module, "{class}").expect("writing to a String cannot fail");
    }
    module
}

struct PythonEnumClass {
    name: &'static str,
    docstring: &'static str,
    members: Vec<PythonEnumMember>,
}

impl Display for PythonEnumClass {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let Self {
            name,
            docstring,
            members,
        } = self;
        write!(
            f,
            "\n\nclass {name}(Enum):\n    \"\"\"{docstring}\"\"\"\n\n"
        )?;
        for PythonEnumMember { name, value } in members {
            writeln!(f, "    {name} = {value}")?;
        }
        Ok(())
    }
}

struct PythonEnumMember {
    name: String,
    value: PythonEnumValue,
}

impl PythonEnumMember {
    /// `geotrace-py` converts a member by its name, and `strum`'s `SCREAMING_SNAKE_CASE` derives
    /// the member name from the variant identifier with the same `heck` function.
    fn new(variant: &impl Debug, value: PythonEnumValue) -> Self {
        Self {
            name: format!("{variant:?}").to_shouty_snake_case(),
            value,
        }
    }
}

enum PythonEnumValue {
    WireCode(u8),
    WireName(String),
}

impl Display for PythonEnumValue {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::WireCode(code) => write!(f, "{code}"),
            Self::WireName(name) => write!(f, "\"{name}\""),
        }
    }
}
