"""Shared infrastructure for QA checks: file iteration, reporting, and exit logic."""

import itertools
import subprocess
from collections.abc import Callable, Iterator
from functools import cache
from pathlib import Path
from typing import NamedTuple

Violation = tuple[Path, int, str]

# Files that declare themselves machine-generated (e.g. dist's release
# workflow). Their comment style is the generator's responsibility, not ours,
# and they are regenerated rather than hand-edited, so the checks skip them.
_GENERATED_MARKERS = ("@generated", "autogenerated by dist")


def repo_root() -> Path:
    """Repository root, resolved from this file's location rather than the
    current working directory.

    `just` runs recipes from imported submodules (such as this `qa` module)
    with the submodule's directory as the working directory, not the repo
    root or the invocation directory — so checks that scanned `Path(".")`
    silently scanned `scripts/qa` instead of the repo, finding nothing.
    """
    return Path(__file__).resolve().parent.parent.parent.parent.parent


@cache
def _tracked_files(root: Path) -> frozenset[Path]:
    """Absolute paths of files git does not ignore under `root`: tracked files
    plus untracked files that aren't matched by `.gitignore`.

    Keeps the checks below from scanning build artifacts, virtualenvs, and
    other generated files that happen to match a checked file pattern.
    """
    output = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        cwd=root,
        capture_output=True,
        check=True,
        text=True,
    ).stdout
    return frozenset(root / p for p in output.split("\0") if p)


def _is_generated(path: Path) -> bool:
    """Whether `path` declares itself machine-generated in its first few lines."""
    try:
        with path.open(encoding="utf-8", errors="ignore") as fh:
            head = list(itertools.islice(fh, 10))
    except OSError:
        return False
    return any(marker in line for line in head for marker in _GENERATED_MARKERS)


def _is_excluded(root: Path, path: Path) -> bool:
    return path not in _tracked_files(root) or _is_generated(path)


def rs_files(root: Path) -> Iterator[Path]:
    for path in sorted(root.rglob("*.rs")):
        if not _is_excluded(root, path):
            yield path


def hash_comment_files(root: Path) -> Iterator[Path]:
    """Yield Python, Just, and CMake source files (uses # comments)."""
    seen: set[Path] = set()
    for pattern in ("*.py", "*.just", "justfile", "CMakeLists.txt", "*.cmake"):
        for path in root.rglob(pattern):
            if not _is_excluded(root, path) and path not in seen:
                seen.add(path)
    yield from sorted(seen)


def c_family_files(root: Path) -> Iterator[Path]:
    """Yield C and C++ source and header files."""
    seen: set[Path] = set()
    for pattern in ("*.c", "*.h", "*.cpp", "*.hpp"):
        for path in root.rglob(pattern):
            if not _is_excluded(root, path) and path not in seen:
                seen.add(path)
    yield from sorted(seen)


def yaml_files(root: Path) -> Iterator[Path]:
    """Yield YAML files (workflow definitions, configuration)."""
    seen: set[Path] = set()
    for pattern in ("*.yml", "*.yaml"):
        for path in root.rglob(pattern):
            if not _is_excluded(root, path) and path not in seen:
                seen.add(path)
    yield from sorted(seen)


def _labelled_lines(tag: str, lines: list[str]) -> None:
    for i, text in enumerate(lines):
        prefix = f"  = {tag}: " if i == 0 else "          "
        print(f"{prefix}{text}")


def report(
    check: str,
    title: str,
    violations: list[Violation],
    note: list[str],
    help: list[str],
) -> None:
    print(f"error[{check}]: {title}\n")
    for path, lineno, line in violations:
        print(f"  --> {path}:{lineno}")
        print("   |")
        print(f"   |  {line}")
        print("   |")
    _labelled_lines("note", note)
    _labelled_lines("help", help + [f'// [qa-allow-{check}, reason = "why this is acceptable"]'])


class Check(NamedTuple):
    """A single QA check: how to find its violations and how to report them."""

    name: str
    title: str
    collect: Callable[[Path], list[Violation]]
    note: list[str]
    help: list[str]


def run_check(check: Check, root: Path) -> bool:
    """Run `check` against `root`, printing a report if it finds violations.

    Returns `True` if any violations were found.
    """
    violations = check.collect(root)
    if violations:
        report(check.name, check.title, violations, check.note, check.help)
        return True
    return False
