# @generated by generate_bindings.rs

from . import Unit as _Unit

class UnitCatalog:
    DEG: _Unit
    M: _Unit
    NM: _Unit
    UM: _Unit
    MM: _Unit
    CM: _Unit
    KM: _Unit
    KM_PER_H: _Unit
    M_PER_S: _Unit
    MM_PER_S: _Unit
    CM_PER_S: _Unit
    KN: _Unit
    M_PER_S2: _Unit
    MM_PER_S2: _Unit
    CM_PER_S2: _Unit
    G: _Unit
    UG: _Unit
    MG: _Unit
    KM_PER_H_PER_S: _Unit
    NS: _Unit
    US: _Unit
    MS: _Unit
    S: _Unit
    MIN: _Unit
    H: _Unit
    PERCENT: _Unit
    PER_S: _Unit
    PER_MIN: _Unit
    PER_H: _Unit
