[package]
name = "gt-sky"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
egui.workspace = true
gt-types = { path = "../gt-types" }
gt-ui-theme = { path = "../gt-ui-theme" }

[dev-dependencies]
chrono.workspace = true
gt-test-utils = { path = "../gt-test-utils", features = ["snapshot"] }
rstest.workspace = true
strum.workspace = true

[lints]
workspace = true
