[package]
name = "gt-ui-theme"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
egui.workspace = true
gt-types = { path = "../gt-types" }
strum.workspace = true

[lints]
workspace = true
