[package]
name = "gt-types"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
bon.workspace = true
chrono.workspace = true
geo-types.workspace = true
geotrace-units = { path = "../../sdk/rust/geotrace-units" }
rstar.workspace = true
serde.workspace = true
strum.workspace = true
uom.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
