[package]
name = "gt-io"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
geotrace-sdk = { path = "../../geotrace-sdks/geotrace-sdk" }
gt-data-ops = { path = "../gt-data-ops" }
gt-types = { path = "../gt-types" }
thiserror.workspace = true
uom.workspace = true

[dev-dependencies]
gt-test-utils = { path = "../gt-test-utils" }
tempfile = "3"

[lints]
workspace = true
