[package]
name = "gt-history"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
dirs.workspace = true
gt-types = { path = "../gt-types" }
gt-history-backend-pure = { path = "../gt-history-backend-pure", optional = true }
gt-history-backend-sys = { path = "../gt-history-backend-sys", optional = true }

[features]
default = ["backend-pure"]
backend-pure = ["dep:gt-history-backend-pure"]
backend-sys = ["dep:gt-history-backend-sys"]

[dev-dependencies]
tempfile.workspace = true
hdf5-pure.workspace = true

[lints]
workspace = true
