[package]
name = "gt-loaded-files"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
gt-fmt = { path = "../gt-fmt" }
gt-history-types = { path = "../gt-history-types" }
gt-types = { path = "../gt-types" }

[dev-dependencies]
chrono.workspace = true
gt-test-utils = { path = "../gt-test-utils" }
rstest.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
