[package]
name = "gt-query"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
geotrace-sdk-units = { path = "../../sdk/rust/geotrace-sdk-units" }
gt-jam = { path = "../gt-jam" }
gt-solar = { path = "../gt-solar" }
gt-types = { path = "../gt-types" }
logos.workspace = true
nalgebra.workspace = true
strum.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true
rstest.workspace = true
serde.workspace = true

[lints]
workspace = true
