[package]
name = "nav-types"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bon.workspace = true
chrono.workspace = true
geo.workspace = true
geo-types.workspace = true
nav-geo-math = { path = "../nav-geo-math" }
uom.workspace = true

[lints]
workspace = true
