#!/usr/bin/env bash
set -euo pipefail
# sdk/c/geotrace.h is generated by `cbindgen` (sdk/rust/geotrace-c/cbindgen.toml), not hand-formatted.
find sdk/c sdk/cpp \( -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" \) \
    -not -path "*/build/*" -not -path "sdk/c/geotrace.h" | sort | xargs clang-format -i
