#!/usr/bin/env bash
set -euo pipefail

# sdk/c/geotrace.h is generated by `cbindgen` (sdk/rust/geotrace-c/cbindgen.toml), not hand-formatted.
mapfile -t FILES < <(find sdk/c \( -name "*.c" -o -name "*.h" \) \
    -not -path '*/build/*' -not -path 'sdk/c/geotrace.h')
clang-format -i "${FILES[@]}"
