[package]
name = "gt-data-ops"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
geo-types.workspace = true
gt-geo-math = { path = "../gt-geo-math" }
gt-types = { path = "../gt-types" }
rstar.workspace = true
uom.workspace = true
vec1.workspace = true

[lints]
workspace = true
