[package]
name = "geotrace-c"
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT"

[lib]
crate-type = ["cdylib", "staticlib"]
doctest = false
test = false

[[bin]]
name = "gen_fixture"

[dependencies]
chrono.workspace = true
geotrace-sdk = { path = "../geotrace-sdk" }

[lints]
workspace = true
