[package]
name = "gt-ionex-store"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false
# All tests are integration tests against real archive files.
test = false

[dependencies]
chrono.workspace = true
gt-hdf5-archive = { path = "../gt-hdf5-archive" }
gt-ionex = { path = "../gt-ionex" }
hdf5.workspace = true
log.workspace = true
parking_lot.workspace = true
thiserror.workspace = true

[dev-dependencies]
gt-test-utils = { path = "../gt-test-utils", features = ["archive"] }
gt-types = { path = "../gt-types" }
rstest.workspace = true
tempfile.workspace = true

[lints]
workspace = true
