#!/usr/bin/env python3
"""Write a basic .gtd file from a hardcoded GPS track.

This example shows the minimal workflow: create a NavFileBuilder,
add a series of NavFix objects, call finish(), and write to disk.
"""

from __future__ import annotations

import tempfile
from datetime import UTC, datetime, timedelta
from pathlib import Path

from geotrace_sdk import NavFileBuilder, NavFix

# Roughly London → Slough → Oxford via the A4/M4 corridor.
TRACK = [
    # (`lat`, `lon`, `heading_deg`, `speed_mps`)
    (51.5074, -0.1278, 75.0, 0.0),  # London, stationary start
    (51.5513, -0.4055, 72.0, 25.0),  # Chiswick
    (51.5817, -0.7417, 74.0, 27.0),  # Slough outskirts
    (51.6017, -1.0334, 76.0, 27.0),  # Maidenhead
    (51.6234, -1.2866, 80.0, 25.0),  # Oxford approach
    (51.7520, -1.2577, 0.0, 0.0),  # Oxford, stopped
]

base_time = datetime(2024, 6, 1, 9, 0, 0, tzinfo=UTC)

builder = (
    NavFileBuilder()
    .with_title("London → Oxford")
    .with_device("demo-gps")
    .with_notes("Example track generated by write_basic.py")
)

for i, (lat, lon, heading, speed) in enumerate(TRACK):
    builder.add(
        NavFix(
            lat=lat,
            lon=lon,
            gps_time=base_time + timedelta(minutes=i * 30),
            heading=heading,
            speed_mps=speed,
        )
    )

nav_file = builder.finish()

out = Path(tempfile.gettempdir()) / "write_basic.gtd"
nav_file.write_to_file(out)
print(f"Written {len(nav_file.points)} nav points to {out}")
