// @generated by generate_bindings.rs
#[pymethods]
#[allow(non_snake_case, reason = "Python unit constants follow the conventional uppercase spelling")]
impl PyUnit {
#[classattr]
fn DEG() -> Self { Self { inner: Unit::DEG } }
#[classattr]
fn M() -> Self { Self { inner: Unit::M } }
#[classattr]
fn NM() -> Self { Self { inner: Unit::NM } }
#[classattr]
fn UM() -> Self { Self { inner: Unit::UM } }
#[classattr]
fn MM() -> Self { Self { inner: Unit::MM } }
#[classattr]
fn CM() -> Self { Self { inner: Unit::CM } }
#[classattr]
fn KM() -> Self { Self { inner: Unit::KM } }
#[classattr]
fn KM_PER_H() -> Self { Self { inner: Unit::KM_PER_H } }
#[classattr]
fn M_PER_S() -> Self { Self { inner: Unit::M_PER_S } }
#[classattr]
fn MM_PER_S() -> Self { Self { inner: Unit::MM_PER_S } }
#[classattr]
fn CM_PER_S() -> Self { Self { inner: Unit::CM_PER_S } }
#[classattr]
fn KN() -> Self { Self { inner: Unit::KN } }
#[classattr]
fn M_PER_S2() -> Self { Self { inner: Unit::M_PER_S2 } }
#[classattr]
fn MM_PER_S2() -> Self { Self { inner: Unit::MM_PER_S2 } }
#[classattr]
fn CM_PER_S2() -> Self { Self { inner: Unit::CM_PER_S2 } }
#[classattr]
fn G() -> Self { Self { inner: Unit::G } }
#[classattr]
fn UG() -> Self { Self { inner: Unit::UG } }
#[classattr]
fn MG() -> Self { Self { inner: Unit::MG } }
#[classattr]
fn KM_PER_H_PER_S() -> Self { Self { inner: Unit::KM_PER_H_PER_S } }
#[classattr]
fn NS() -> Self { Self { inner: Unit::NS } }
#[classattr]
fn US() -> Self { Self { inner: Unit::US } }
#[classattr]
fn MS() -> Self { Self { inner: Unit::MS } }
#[classattr]
fn S() -> Self { Self { inner: Unit::S } }
#[classattr]
fn MIN() -> Self { Self { inner: Unit::MIN } }
#[classattr]
fn H() -> Self { Self { inner: Unit::H } }
#[classattr]
fn PERCENT() -> Self { Self { inner: Unit::PERCENT } }
#[classattr]
fn PER_S() -> Self { Self { inner: Unit::PER_S } }
#[classattr]
fn PER_MIN() -> Self { Self { inner: Unit::PER_MIN } }
#[classattr]
fn PER_H() -> Self { Self { inner: Unit::PER_H } }
#[getter]
fn label(&self) -> String { self.inner.to_string() }
fn __str__(&self) -> String { self.inner.to_string() }
fn __repr__(&self) -> String { format!("Unit({:?})", self.inner.to_string()) }
fn __hash__(&self) -> u64 { let mut hasher = DefaultHasher::new(); self.inner.hash(&mut hasher); hasher.finish() }
}
