[package]
name = "gt-test-utils"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
geo.workspace = true
geo-types.workspace = true
gt-types = { path = "../gt-types" }
uom.workspace = true

[lints]
workspace = true
