[package]
name = "gt-test-utils"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
snapshot = [
    "dep:egui",
    "dep:egui_kittest",
    "dep:egui-wgpu",
    "dep:egui-phosphor",
    "dep:tempfile",
    "dep:eframe",
]

[dependencies]
chrono.workspace = true
eframe = { workspace = true, optional = true }
egui = { workspace = true, optional = true }
egui-phosphor = { workspace = true, optional = true }
egui-wgpu = { workspace = true, optional = true }
egui_kittest = { workspace = true, optional = true }
geo.workspace = true
geo-types.workspace = true
geotrace-sdk = { path = "../../sdk/rust/geotrace-sdk" }
gt-types = { path = "../gt-types" }
tempfile = { workspace = true, optional = true }
uom.workspace = true

[lints]
workspace = true
