[package]
name = "gt-map"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
bon.workspace = true
chrono.workspace = true
egui.workspace = true
egui-phosphor.workspace = true
gt-filter = { path = "../gt-filter" }
gt-fmt = { path = "../gt-fmt" }
gt-track-builder = { path = "../gt-track-builder" }
gt-types = { path = "../gt-types" }
gt-ui-theme = { path = "../gt-ui-theme" }
gt-ui-types = { path = "../gt-ui-types" }
rstar.workspace = true
smallvec.workspace = true
strum.workspace = true
uom.workspace = true
walkers.workspace = true

[dev-dependencies]
egui_kittest.workspace = true
gt-test-utils = { path = "../gt-test-utils", features = ["snapshot"] }
proptest.workspace = true

[lints]
workspace = true
