[package]
name = "gt-map"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
egui.workspace = true
egui-phosphor.workspace = true
gt-data-ops = { path = "../gt-data-ops" }
gt-types = { path = "../gt-types" }
gt-ui-theme = { path = "../gt-ui-theme" }
rstar.workspace = true
uom.workspace = true
walkers.workspace = true

[dev-dependencies]
egui_extras.workspace = true
egui_kittest = { version = "0.34.3", features = ["wgpu", "snapshot"] }
gt-test-utils = { path = "../gt-test-utils" }
strum.workspace = true

[lints]
workspace = true
