#![expect(
    clippy::expect_used,
    reason = "formatting into an in-memory String is infallible"
)]

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use geotrace_units::Unit;

fn generated_files() -> [(PathBuf, String); 3] {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let mut cpp = String::from(
        "// @generated by generate_bindings.rs\n#ifndef GEOTRACE_UNIT_CATALOG_HPP\n#define GEOTRACE_UNIT_CATALOG_HPP\n\n#include <cstdint>\n\nnamespace geotrace {\n\n",
    );
    cpp.push_str("enum class RecognizedUnit : std::uint8_t {\n");
    for binding in Unit::BINDINGS {
        writeln!(cpp, "    {},", binding.cpp).expect("writing to a String cannot fail");
    }
    cpp.push_str("};\n\ninline const char *recognized_unit_label(RecognizedUnit unit) {\n    switch (unit) {\n");
    for binding in Unit::BINDINGS {
        write!(
            cpp,
            "    case RecognizedUnit::{}:\n        return \"{}\";\n",
            binding.cpp,
            binding.unit.label()
        )
        .expect("writing to a String cannot fail");
    }
    cpp.push_str(
        "    }\n    return nullptr;\n}\n\n} // namespace geotrace\n\n#endif // GEOTRACE_UNIT_CATALOG_HPP\n",
    );

    let mut rust = String::from(
        "// @generated by generate_bindings.rs\n#[pymethods]\n#[allow(non_snake_case, reason = \"Python unit constants follow the conventional uppercase spelling\")]\nimpl PyUnit {\n",
    );
    for binding in Unit::BINDINGS {
        write!(
            rust,
            "#[classattr]\nfn {}() -> Self {{ Self {{ inner: Unit::{} }} }}\n",
            binding.python, binding.rust
        )
        .expect("writing to a String cannot fail");
    }
    rust.push_str(
        "#[getter]\nfn label(&self) -> String { self.inner.to_string() }\nfn __str__(&self) -> String { self.inner.to_string() }\nfn __repr__(&self) -> String { format!(\"Unit({:?})\", self.inner.to_string()) }\nfn __hash__(&self) -> u64 { let mut hasher = DefaultHasher::new(); self.inner.hash(&mut hasher); hasher.finish() }\n}\n",
    );

    let mut pyi = String::from(
        "# @generated by generate_bindings.rs\n\nfrom . import Unit as _Unit\n\nclass UnitCatalog:\n",
    );
    for binding in Unit::BINDINGS {
        writeln!(pyi, "    {}: _Unit", binding.python).expect("writing to a String cannot fail");
    }

    [
        (root.join("cpp/include/geotrace/unit_catalog.hpp"), cpp),
        (root.join("python/geotrace-py/src/unit_catalog.rs"), rust),
        (
            root.join("python/geotrace-py/python/geotrace_sdk/_unit_catalog.pyi"),
            pyi,
        ),
    ]
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let check = env::args().any(|arg| arg == "--check");
    for (path, contents) in generated_files() {
        if check {
            if fs::read_to_string(&path)? != contents {
                return Err(format!("{} is stale", path.display()).into());
            }
        } else {
            fs::write(path, contents)?;
        }
    }
    Ok(())
}
