[package]
name = "gt-side-panel"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
egui.workspace = true
egui-phosphor.workspace = true
gt-fmt = { path = "../gt-fmt" }
gt-types = { path = "../gt-types" }
gt-ui-theme = { path = "../gt-ui-theme" }
uom.workspace = true

[dev-dependencies]
egui_kittest = { version = "0.34.3", features = ["wgpu", "snapshot"] }
gt-data-ops = { path = "../gt-data-ops" }
gt-test-utils = { path = "../gt-test-utils", features = ["snapshot"] }

[lints]
workspace = true
